window.AIRDROP_TASKS = [
  {n:"Amadeus",web:"https://amahub.ama.one/quests?ref=CGXVE3OI",x:"https://x.com/ama_protocol",h:null,img:null,d:"amahub.ama.one",t:"daily",p:"critical",c:"unknown",s:["Hoàn thành nhiệm vụ cá nhân", "Nhiệm vụ mạng xã hội", "Nhiệm vụ agent và skill", "Điểm danh hàng ngày và các nhiệm vụ Amadeus khả dụng"]},
  {n:"Asentum",web:"https://airdrop.asentum.com/",x:"https://x.com/asentum",h:null,img:null,d:"airdrop.asentum.com",t:"daily",p:"high",c:"asentum",s:["Truy cập https://airdrop.asentum.com đăng nhập (ví/mạng xã hội)", "Kết nối ví Asentum (extension/Telegram @AsentumBot)", "Nhận faucet 5 ASE", "Farm XP: giao dịch on-chain/chuyển/deploy contract", "Dùng dApps ASocial/Pay/Subs/Auras swap/LP", "Chạy validator (bond test ASE)", "Giới thiệu/chia sẻ X/báo lỗi", "Tùy chọn stake $ASE thật 30 ngày để nhân x2-x10", "Theo dõi XP/bảng xếp hạng"]},
  {n:"CZR Genesis Airdrop",web:"https://czrex.com",x:"https://x.com/czrexchange",h:null,img:null,d:"czrex.com",t:"daily",p:"medium",c:"ethereum",s:["Mở https://airdrop.czrex.com/airdrop?referral_code=GLN487XI kết nối ví EVM", "Hoàn thành nhiệm vụ bắt buộc: Theo dõi X @czrexchange", "Theo dõi/Tham gia Telegram", "Đăng bài về CZR Token trên X", "Đăng ký CZR Exchange", "Hoàn thành nhiệm vụ bổ sung: Discord", "Kết nối X", "Nhiệm vụ hàng ngày (điểm cập nhật hàng ngày)", "Mời bạn bè để nhận thêm điểm"]},
  {n:"EarnList",web:"https://earnlist.app/r/fRlj_328",x:"https://x.com/Earnlist",h:null,img:null,d:"earnlist.app",t:"one_time",p:"medium",c:"other",s:["Kết nối ví (ví = tài khoản)", "Nhập Gmail nếu được yêu cầu", "Nhận 500 điểm + 100 điểm mỗi lượt giới thiệu", "Chia sẻ link giới thiệu để leo hạng danh sách chờ (dự kiến đóng ~22/09/2026)"]},
  {n:"XDAO",web:"https://xdao.app",x:"https://x.com/xdaoapp",h:null,img:null,d:"xdao.app",t:"one_time",p:"high",c:"solana",s:["Mở bot XDAO TON (t.me/xdao_ton_bot) → mục Airdrop → kết nối ví TON → liên kết ví Solana non-custodial (Phantom/Solflare) trước snapshot 20/09/2026 14:00 UTC", "Dùng Change Wallet để sửa nếu cần", "Đồng thời kết nối ví Arbitrum non-custodial trước 25/09/2026 để claim $XDAO tại TGE", "Kiểm tra đủ điều kiện trong Mini App"]},
  {n:"Fliptfun Testnet",web:"https://testnet.flipt.fun/",x:"https://x.com/Fliptfun",h:null,img:null,d:"testnet.flipt.fun",t:"one_time",p:"medium",c:"arc",s:["Kết nối ví", "Nhận Flipt test USDC", "Tạo token/giao dịch trên bonding curve", "Giữ vị thế bonded đến khi graduation", "Leo bảng xếp hạng", "Tránh spam/lạm dụng"]},
  {n:"KaleidoFi",web:"https://kaleidofi.xyz/waitlist?ref=aqgssv74",x:"https://x.com/KaleidoFi",h:null,img:null,d:"kaleidofi.xyz",t:"one_time",p:"medium",c:"arc",s:["Mở link danh sách chờ", "Kết nối ví (MetaMask/Coinbase/Rainbow/WalletConnect)", "Nhận 100 điểm chào mừng", "Theo dõi X chính thức và repost để nhận điểm thưởng", "Thực hiện giao dịch đầu tiên trên Arc testnet/mainnet", "Giao dịch agent đầu tiên trên Kaleido", "Mời qua giới thiệu"]},
  {n:"Forecast",web:"https://forecastprotocol.xyz/mainnet-whitelist/",x:"https://x.com/ForecastFDN",h:null,img:null,d:"forecastprotocol.xyz",t:"one_time",p:"medium",c:"ethereum",s:["Hoàn thành nhiệm vụ Arkada", "Nhận điểm/SBT/vòng quay và đăng ký ví ETH trong form whitelist mainnet"]}
];
