window.AIRDROP_TASKS = [
  {n:"Amadeus",web:"https://amahub.ama.one/quests?ref=CGXVE3OI",x:"https://x.com/ama_protocol",h:null,img:null,d:"amahub.ama.one",t:"daily",p:"critical",c:"unknown",s:["Complete individual quests", "Social tasks", "Agent and skill tasks", "Daily check-ins and available Amadeus quests"]},
  {n:"Asentum",web:"https://airdrop.asentum.com/",x:"https://x.com/asentum",h:null,img:null,d:"airdrop.asentum.com",t:"daily",p:"high",c:"asentum",s:["Go to https://airdrop.asentum.com sign in (wallet/social)", "Connect Asentum wallet (extension/Telegram @AsentumBot)", "Claim faucet 5 ASE", "Farm XP: on-chain tx/transfer/deploy contract", "Use dApps ASocial/Pay/Subs/Auras swap/LP", "Run validator (bond test ASE)", "Referral/share X/bug report", "Optional stake real $ASE 30 days for multiplier x2-x10", "Track XP/leaderboard"]},
  {n:"CZR Genesis Airdrop",web:"https://czrex.com",x:"https://x.com/czrexchange",h:null,img:null,d:"czrex.com",t:"daily",p:"medium",c:"ethereum",s:["Open https://airdrop.czrex.com/airdrop?referral_code=GLN487XI connect EVM wallet", "Complete mandatory quests: Follow X @czrexchange", "Follow/Join Telegram", "Post about CZR Token on X", "Sign up for CZR Exchange", "Complete additional tasks: Discord", "Connect X", "Daily quests (points update daily)", "Refer friends to earn extra points"]},
  {n:"EarnList",web:"https://earnlist.app/r/fRlj_328",x:"https://x.com/Earnlist",h:null,img:null,d:"earnlist.app",t:"one_time",p:"medium",c:"other",s:["Connect wallet (wallet = account)", "Enter Gmail if prompted", "Claim 500 points + 100 points per referral", "Share referral link to climb waitlist rankings (waitlist expected to close ~2026-09-22)"]},
  {n:"XDAO",web:"https://xdao.app",x:"https://x.com/xdaoapp",h:null,img:null,d:"xdao.app",t:"one_time",p:"high",c:"solana",s:["Open XDAO TON bot (t.me/xdao_ton_bot) -> Airdrop section -> connect TON wallet -> link non-custodial Solana wallet (Phantom/Solflare) before snapshot 2026-09-20 14:00 UTC", "Use Change Wallet to fix if needed", "Also connect non-custodial Arbitrum wallet (0x…) before 2026-09-25 to claim $XDAO at TGE", "Check eligibility in Mini App"]},
  {n:"Fliptfun Testnet",web:"https://testnet.flipt.fun/",x:"https://x.com/Fliptfun",h:null,img:null,d:"testnet.flipt.fun",t:"one_time",p:"medium",c:"arc",s:["Connect wallet", "Claim Flipt test USDC", "Create tokens/trade on bonding curve", "Hold bonded positions until graduation", "Climb leaderboard", "Avoid spam/abuse"]},
  {n:"KaleidoFi",web:"https://kaleidofi.xyz/waitlist?ref=aqgssv74",x:"https://x.com/KaleidoFi",h:null,img:null,d:"kaleidofi.xyz",t:"one_time",p:"medium",c:"arc",s:["Open waitlist link", "Connect wallet (MetaMask/Coinbase/Rainbow/WalletConnect)", "Claim 100 welcome points", "Follow official X and repost for bonus points", "Do first trade on Arc testnet/mainnet and first agent trade on Kaleido", "Invite via referral"]},
  {n:"Forecast",web:"https://forecastprotocol.xyz/mainnet-whitelist/",x:"https://x.com/ForecastFDN",h:null,img:null,d:"forecastprotocol.xyz",t:"one_time",p:"medium",c:"ethereum",s:["Complete Arkada quest", "Claim points / SBT / spin", "Register ETH wallet in mainnet whitelist form"]}
];
